version: "3.9"
services:
  backend:
    build: src/backend
    container_name: ToDo-backend
    tty: true
    network_mode: host
  frontend:
    build: src/frontend
    container_name: ToDo-frontend
    tty: true
    depends_on:
      - backend