# Generated by Django 4.1.3 on 2022-11-08 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
