# Generated by Django 4.1.3 on 2022-11-08 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1024)),
                ('done', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2022, 11, 8, 13, 28, 57, 757372))),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.list')),
            ],
        ),
    ]
