# Generated by Django 4.1.3 on 2022-11-15 21:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_note_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="due_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="notes.list",
            ),
        ),
    ]
